version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/dashboard/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
